# docker-compose.yml
version: '3.8'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.17.9"
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"